### ISSUE TITLE
Retina scale fuzzy?

### ISSUE THREAD

**Issue by kreeger** [AlexDenisov/FontasticIcons#10]
I know you've got [this line of code](https://github.com/AlexDenisov/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIIconLayer.m#L66) that should take this into consideration, but as of the latest pull request that was merged, I'm seeing fuzziness on retina devices for icons. Any idea what's up?

![Screen Shot 2013-01-02 at 2 29 58 PM](https://f.cloud.github.com/assets/58783/39206/7485c370-551b-11e2-8087-b73b37ecb996.png)

I don't quite understand a lot of CoreText stuff yet, but is it possible something's up in `FIIconLayer+FIRenderer.m`, like in `-setTransformForContext:bounds:iconBounds:`, or perhaps `-scaleForBounds:iconBounds:`?

**Comment by AlexDenisov** [comment]
Thanks, I'll review this issue soon.
@dnalot, maybe you have an ideas?

**Comment by texastoland** [comment]
I haven't confirmed but I think it's this:

> **Note:** `CATextLayer` disables sub-pixel antialiasing when rendering text. Text can only be drawn using sub-pixel antialiasing when it is composited into an existing opaque background at the same time that it's rasterized. There is no way to draw text with sub-pixel antialiasing by itself, whether into an image or a layer, in advance of having the background pixels to weave the text pixels into. Setting the `opacity` property of the layer to `YES` does not change the rendering mode.

([CATextLayer](https://developer.apple.com/library/mac/#documentation/GraphicsImaging/Reference/CATextLayer_class/Introduction/Introduction.html) Class Reference)

I found a solution on [SO](http://stackoverflow.com/a/4494315/672921) I plan to implement next week in another category building on `FIIconLayer(FIRenderer)`. But I want to vet it out for performance. My other idea is making the icon layer composite itself onto its target by registering as its `delegate`.

@kreeger Could you help me verify? I tried `CALayer#opaque` and `CALayer#opacity` without success using:
- `CALayer#backgroundColor`
- `CGContextFillRect()` with `UIColor#setFillColor`
- `CGContextFillRect()` with `CGContextSetFillColorWithColor()`

**Comment by kreeger** [comment]
@dnalot: I can verify those don't work, either. I eagerly await your fix! :smiley:

**Comment by texastoland** [comment]
I just realized you said "as of latest"…did it render differently before? Would you mind uploading a screenshot and sample project? Improving rendering was one of my goals so I hope didn't exacerbate it!

**Comment by kreeger** [comment]
Here's a before shot.

![Screen Shot 2013-01-04 at 12 34 54 PM](https://f.cloud.github.com/assets/58783/43854/77be5e66-569d-11e2-9860-05eba8e38791.png)

And when I say "before," the version I've been using was [tagged v0.1.2](https://github.com/AlexDenisov/FontasticIcons/tree/0.1.2). I'll see if I can fire up a sample project, but all I'm doing is using the same methods before the CoreText refactor.

``` objective-c
FIIconView *iconView = [[FIIconView alloc] initWithFrame:CGRectMake(0, 0, 40, 40)];
iconView.icon = [FIFontAwesomeIcon homeIcon];
iconView.iconColor = [UIColor grayColor];
iconView.backgroundColor = [UIColor clearColor];
iconView.padding = 2.0;
[self.view addSubview:iconView];
```

**Comment by texastoland** [comment]
Wow yeah I'll fire it up as soon as you do! Is it still blurry without padding? If not I can fix inside an hour.

**Comment by kreeger** [comment]
Yep, definitely still blurry without padding. Also, I just realized - all you have to do is fire up the sample project included with FontasticIcons, and run it in a simulator for a retina-sized device. The font list controller looks good, because the icons there are being rendered using `-imageWithBounds:color:`. On `FIViewController` though, since they're being added as subviews directly without being rendered to images, they're blurry.

**Comment by texastoland** [comment]
Reproduced.

**Comment by texastoland** [comment]
Positively [identified](http://stackoverflow.com/a/9479176/672921). The line @kreeger noticed to render for retina is getting overriden by its delegating view. Merging into into my pull request for @AlexDenisov along with a simplification of my maths using `CALayer#geometryFlipped` and `CGContextSetTextMatrix` tonight.

**Comment by kreeger** [comment]
You're a rock star. Thanks for your work, @dnalot!

**Comment by texastoland** [comment]
Click for hi-res:

| 0.1.2 | 0.2.0 regression | 0.2.0 fix |
| --- | --- | --- |
| ![0.1.2](https://f.cloud.github.com/assets/48431/44566/3c31df92-56cc-11e2-886c-bc3482badb11.png) | ![0.2.0 regression](https://f.cloud.github.com/assets/48431/44565/3c040658-56cc-11e2-9f54-bc3b95b6a7b2.png) | ![0.2.0 fix](https://f.cloud.github.com/assets/48431/44564/3bfe71a2-56cc-11e2-9a2a-7b1e1d238ef3.png) |
