### ISSUE TITLE
Iconic font wrong icons

### ISSUE THREAD

**Issue by beholdr** [AlexDenisov/FontasticIcons#11]
At least two icons in Iconic font are confused between each other: `xIcon` and `xAltIcon` shows check instead of cross, and `checkIcon` and `checkAltIcon` shows cross instead of check.

**Comment by AlexDenisov** [comment]
Thank you, I'll review it soon.

**Comment by texastoland** [comment]
+@kreeger

**Comment by kreeger** [comment]
I can also look into this and include it in my pull request for font name refactoring. Seems like as good of a time as any!

**Comment by AlexDenisov** [comment]
<blockquote>I can also look into this and include it in my pull request for font name refactoring.</blockquote>

:+1:

**Comment by texastoland** [comment]
@AlexDenisov This should still be open for a little while. I was waiting to finish strings and refactoring to look closer.
- [ ] Also sanity Entypo/Social

**Comment by texastoland** [comment]
@beholdr Do you still need this?

**Comment by beholdr** [comment]
@dnalot nope =)
