### ISSUE TITLE
Different icon names for Font Awesome fonts?

### ISSUE THREAD

**Issue by kreeger** [AlexDenisov/FontasticIcons#13]
This is probably a matter of taste, but I've been using a fork of my own lately that uses correct Font Awesome names for each of the FIFontAwesomeIcon methods, from the [Font Awesome website](http://fortawesome.github.com/Font-Awesome/) (makes it much easier to find icons to use). Is this something you're interested in merging into master? (Keep in mind, I've not done anything about the 3.0 stuff.)

If so, I'll submit a pull request after I add in backwards-compatibility methods that won't break others' API. What do you think?

**Comment by texastoland** [comment]
I've been wondering about refactoring that:
- [x] Maps in `strings` files instead of hardcoded
- [x] Real proxy methods forwarding invocations instead of hardcoded
- [x] Continue to maintain `@interface` methods but auto-implemented

Then you could add your mappings to Font Awesome's `strings` file, named in its `@interface`, marking duplicates with the `DEPRECATED_ATTRIBUTE` macro?

**Comment by kreeger** [comment]
I like that idea. I may work on that some this weekend as time permits.
Seems like a smart idea.

_Ben Kreeger_ | ben@kree.gr | _sent via mobile_

On Jan 4, 2013, at 7:01 PM, Jonathan Toland notifications@github.com
wrote:

I've been wondering about refactoring that:
1. Maps in strings files instead of hardcoded
2. Real proxy methods forwarding invocations instead of hardcoded
3. Continue to maintain @interface methods but auto-implemented

Then you could add your mappings to Font Awesome's strings file, named in
its @interface, marking duplicates with the DEPRECATED_ATTRIBUTE macro?

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlexDenisov/FontasticIcons/issues/13#issuecomment-11906788.

**Comment by texastoland** [comment]
:metal:

**Comment by AlexDenisov** [comment]
Thank you, guys. This is a good idea. I'm totally agreed. :smile:

**Comment by kreeger** [comment]
I'm missing something important; when I move those sequences into `.strings` files, and read them in as a dict, the `\U000` is being trimmed off and the text is showing up as the four-digit code. I'm kinda stumped; any ideas?

![iOS Simulator Screen shot Jan 7 2013 11 24 47 AM](https://f.cloud.github.com/assets/58783/47913/45591480-58ef-11e2-80bd-eeab6f4e9f9f.png)

**Comment by texastoland** [comment]
Which branch? I'll look tonight!

**Comment by AlexDenisov** [comment]
+1, push it to remote so we can review this issue.

**Comment by kreeger** [comment]
Yeah, it's on my `names` branch. https://github.com/kreeger/FontasticIcons/tree/names

**Comment by texastoland** [comment]
[Encode](https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html) them as `\Udddd` to get just the glyph.

**Comment by kreeger** [comment]
You have made my morning, sir. Evidently I glossed right over that looking at that doc. Thanks!

**Comment by texastoland** [comment]
Yessir looking good :metal: Refactor dictionary loading into `FIIcon` based on `+ fontSetName`?

**Comment by kreeger** [comment]
Yeah, I plan on cleaning that up. What about the strings that have a surrogate character, like those in Entypo and FontAwesome?

```
"camera" = "\U0001F4F7";
```

The tree I'm barking up is how to correctly represent [surrogate code points](http://www.unicode.org/glossary/#surrogate_code_point) in `.strings` files. I'm doing some digging right now. Problem is, I get into [stuff like this](http://stackoverflow.com/questions/6458708/converting-an-nsstring-to-and-from-utf32) and I feel like a fish out of water.

**Comment by kreeger** [comment]
I've found that if I store it as a hex string...

```
"cc-nc-eu" = "0x1F548";
```

Then I can parse it to hex and get the surrogate pair that way, and convert that to an NSString. Since I've not done much of this… is this filthy, nasty code? Or is this okay?

``` objective-c
+ (NSString *)iconKeyForName:(NSString *)aName {
    NSString *iconKey = [[self metaIconsDictionary] valueForKey:aName];
    if (iconKey != nil) {
        if (iconKey.length == 1) return iconKey;
        UniChar c[2];
        unsigned result = 0;
        NSScanner *scanner = [NSScanner scannerWithString:iconKey];
        [scanner scanHexInt:&result];
        if (CFStringGetSurrogatePairForLongCharacter(result, c)) {
            return [[NSString alloc] initWithCharacters:c length:2];
        } else {
            return iconKey;
        }
    } else return nil;
}
```

If we were to store all the values as hex, this should work.

``` objective-c
{
    UniChar c[2];
    unsigned result = 0;
    [[NSScanner scannerWithString:iconKey] scanHexInt:&result];
    if (CFStringGetSurrogatePairForLongCharacter(result, c)) {
        return [[NSString alloc] initWithCharacters:c length:2];
    } else {
        return [[NSString alloc] initWithCharacters:c length:1];
    }
}
```

How does this feel? https://github.com/kreeger/FontasticIcons/commit/269c64f6f5f92310d529f41b24476474383d5835

**Comment by texastoland** [comment]
`+ iconKeyForName:` shouldn't change. If anything it'd be initialization. But researching. Also online on Skype.

**Comment by texastoland** [comment]
> To escape an extended character that is not in the Basic Multilingual Plane, the character is represented as a twelve-character sequence, encoding the UTF-16 surrogate pair. So, for example, a string containing only the G clef character (U+1D11E) may be represented as `\uD834\uDD1E`.

[Helpful](http://blog.manbolo.com/2012/10/29/supporting-new-emojis-on-ios-6)?

**Comment by kreeger** [comment]
We hashed this out back and forth (on Skype) but I still couldn't find a way to store these surrogate pairs in a strings file (we even tried JSON files). There's _gotta_ be a way, though, because many of the emoji characters are surrogate-paired characters; seems like a weird oversight to not be able to store those in a localization file format. @dnalot said he'd try to give it a shot this evening.

**Comment by kreeger** [comment]
And `HEAD` on my `names` branch has the latest changes, including the refactoring of dict loading into `FIFont`.

**Comment by texastoland** [comment]
Surrogate pairs were indeed the right track but `\Udddd` must be capitalized and I had to both clean and delete my [sample app](https://github.com/dnalot/Sandbox/blob/localizing-surrogate-pairs/Sandbox/en.lproj/CSViewController.strings#L3) from the simulator between updating `strings`.

**Comment by kreeger** [comment]
I've reverted my branch back to using the non-hex values, but I still can't seem to get anything with a high surrogate of `\U0001` to show up, even after cleaning / rebuilding. On iOS5, the output of the string is blank. On iOS6, it's this funky character all over the place.

## iOS 5

![iOS Simulator Screen shot Jan 7 2013 5 35 57 PM](https://f.cloud.github.com/assets/58783/48810/03a5ccca-5923-11e2-93dd-b336df2239b5.png)

## iOS 6

![iOS Simulator Screen shot Jan 7 2013 5 35 09 PM](https://f.cloud.github.com/assets/58783/48808/ea004872-5922-11e2-9143-f912aa6b3ae2.png)

You can download it and take a look; maybe there's something in the project I'm not seeing. I'm still stuck.

**Comment by texastoland** [comment]
Surrogate pairs have to be [looked up](http://www.i18nguy.com/unicode/surrogatetable.html) or [calculated](http://www.russellcottrell.com/greek/utilities/SurrogatePairCalculator.htm) (there's a couple Wikipedias [about](http://en.wikipedia.org/wiki/UTF-16#Code_points_U.2B10000_to_U.2B10FFFF) [why](http://en.wikipedia.org/wiki/Mapping_of_Unicode_characters#Surrogates)). Looking promising!

**Comment by kreeger** [comment]
That's exactly it; I need to calculate the rest out, but it's working now.

If only there was an emoji that would show my immense gratitude for the help you've given me… I know! :beer:

I've whipped [this script](https://gist.github.com/4480326) up… I'm just going to batch process the files.

**Comment by kreeger** [comment]
That's in the bank, now I'm going to work on dynamic invocations.

**Comment by texastoland** [comment]
Snazzy script :+1: `FIIconView` is there if you like a proxy example.

**Comment by kreeger** [comment]
@dnalot:

I… actually have no idea how to get started with dynamic invocations; it's something I've never done before (in Objective-C). I've read up some on `NSProxy` and `NSMethodInvocation` and stuff, but I can't nail it down. Are we going to remove all the methods from the font-specific subclasses? How will the compiler know what's a valid method at runtime? It's kinda still over my head at this point.

If you'd like to take a stab at it (and show me how it's done :)), I can submit my pull request and you can take it from there. I've got everything else in there besides the dynamic class method invocation.

**Comment by texastoland** [comment]
Did you see [`FIIconView`](https://github.com/kreeger/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIIconView.m#L39)? It forwards all but a couple properties on to `FIIconLayer` for configuration. It's shockingly simple once you've seen it. Basically you override one method for dynamic invocations and another to fake interface methods. But all you need is the former. I'll be on Skype a few more minutes too. Date tonight :joy_cat:

**Comment by kreeger** [comment]
Ah, I'll be on my commute home in a few minutes, so no Skype for me this evening; I did see `FIIconView` though. I can understand forwarding messages to an object that knows it responds to them. I just didn't know if we were going to be removing all the class messages from, say, `FIFontAwesomeIcon` and just let it respond to methods based on entries in the dictionary.

So in other words, `[FIFontAwesomeIcon starIcon]`, once that `+starIcon` message is removed and fully dynamic, throws a "doesn't respond to selector" error. I suppose the part I don't understand is letting the compiler / runtime know that _yes, it is a valid selector, just call `iconWithName:`_. [This is what I had, commented out](https://github.com/kreeger/FontasticIcons/blob/c8f94020192c0fa6aa1a0ba356a470e9b1ec6ead/FontasticIcons/Sources/Classes/FIIcon.m#L92) prior to removing it. Was I barking up the right tree at all?

**Comment by texastoland** [comment]
Exactly it verbatim! Any error? You should only need `methodSignatureForSelector:` without interface methods and then you would still base it off your dictionary. I'll pull it down tomorrow if you hit a wall.

**Comment by texastoland** [comment]
That's assuming the icon name is getting extracted exactly like the dictionary key?

**Comment by kreeger** [comment]
Yeah, that's the idea. I'll give the NSMethodInvocation stuff another
shot tomorrow… sounds like that's where I need to do more
investigating there!

**Comment by texastoland** [comment]
Any luck?

**Comment by kreeger** [comment]
I've actually had zero time to work on it last week, and probably won't have any chance within the next couple of weeks, either (work's swelled up again)! If you want to take a look, be my guest!

**Comment by texastoland** [comment]
I'm headed on vacay so I'll let you know if I merge it before you finish :v:

**Comment by texastoland** [comment]
If you won't have time this weekend I'll plan to merge your branch then?

**Comment by kreeger** [comment]
Yeah, go for it!

**Comment by texastoland** [comment]
[Done](https://github.com/dnalot/FontasticIcons/commits/patch-1). @kreeger I massively rebased your changes (for semantic progression) but otherwise mostly your work besides the proxy and attributed as such. Would you mind testing it out? @AlexDenisov I'm waiting to close #11 and [nix the manager](https://github.com/kreeger/FontasticIcons/commit/078dadec3849db91a4cd0ee89b8936fc3808b742#commitcomment-2400231) before submitting a PR.

**Comment by AlexDenisov** [comment]
@kreeger, @dnalot, thank you, guys. That's awesome. Now it looks much better, than my implementation.

<blockquote>nix the manager</blockquote>

Could you get this done?

**Comment by kreeger** [comment]
I'll test either this afternoon or tomorrow for sure. Thanks!

**Comment by texastoland** [comment]
It shouldn't take more than a quarter day next weekend. It will be even easier now that `FIIcon` is primarily responsible for its own lookups. The only API change would be requiring ARC but it's been around since 4.0 which the podspec already targets. #11 may take longer. I'd like to review the links at the top of each [`strings`](https://github.com/dnalot/FontasticIcons/tree/patch-1/FontasticIcons/Sources/Resources/Strings) file and make sure all icons are accounted for. In the meantime I'm back on my client project.

**Comment by kreeger** [comment]
@dnalot you want me to test with your `patch-1` branch, right?

**Comment by texastoland** [comment]
Yessir!

**Comment by kreeger** [comment]
@dnalot: it works fine in the sample application if I call the icon using its string key, but when I use a method name, the app throws an `unrecognized selector` exception. So in other words, _this_ works…

``` objective-c
[FIIcon iconWithName:@"star" fontSetName:cell.textLabel.text]
```

…but neither of _these_ do.

``` objective-c
[FIFontAwesomeIcon starIcon];
[FIEntypoIcon starIcon];
[FIIconicIcon starIcon];
```

They fail with this exception (substitute class name where appropriate, obviously).

```
+[FIIconicIcon starIcon]: unrecognized selector sent to class 0xcb00
```

Interestingly enough, the IDE shows those are valid methods on those classes; they're highlighted, and travelling to their definition takes me to where they are in code.

**Comment by AlexDenisov** [comment]
I could fix this, later (after few hours)

**Comment by texastoland** [comment]
Bummer! I'll look too. Sounds like I need to put back `-methodSignatureForSelector:`. Thx for the detective work.

**Comment by texastoland** [comment]
[Fixed](https://github.com/dnalot/FontasticIcons/commit/edc409cc8ad073c66be1fcdbba22bd2843b422d1), [verified](https://github.com/dnalot/FontasticIcons/blob/edc409cc8ad073c66be1fcdbba22bd2843b422d1/FontasticIcons/Sample/FIFontListViewController.m#L48), and [simplified](https://github.com/dnalot/FontasticIcons/blob/edc409cc8ad073c66be1fcdbba22bd2843b422d1/FontasticIcons/Sources/Classes/FIIconView.m#L38) `FIIconView` in the process :neckbeard:

**Comment by AlexDenisov** [comment]
I've also fixed this, but I use [another solution](https://github.com/AlexDenisov/FontasticIcons/commit/6d595e3dd4675e269e938e0e97677d6a159632fb).
We should select which one goes into master :)

**Comment by texastoland** [comment]
I considered that but took the conventional way out. Yours is more performant overall though. Emending mine.

**Comment by kreeger** [comment]
You guys are friggin' wizards. :beer:

**Comment by texastoland** [comment]
@AlexDenisov [Variation](https://github.com/dnalot/FontasticIcons/blob/edc409cc8ad073c66be1fcdbba22bd2843b422d1/FontasticIcons/Sources/Classes/FIIcon.m#L96) using Obj-C method instead?

**Comment by AlexDenisov** [comment]
<blockquote> Variation using Obj-C method instead?</blockquote>

:+1: Could you open PR?

**Comment by texastoland** [comment]
Would you rather wait for the rest? I started refactoring the manager yesterday but put too much in `FIIcon` before realizing `FIFont` should be doing about half that work (especially loading and storing glyph dictionaries). I should have a chance to finish Saturday.

**Comment by AlexDenisov** [comment]
Yes, sure. Don't take your time ;-)

**Comment by texastoland** [comment]
Should automatically close with PR #19.

**Comment by texastoland** [comment]
Merged in `development`. Radical props @kreeger for groundwork (around half that PR including nixing the manager based on our discussion) :fist:
