### ISSUE TITLE
Unit/Behavior Testing

### ISSUE THREAD

**Issue by texastoland** [AlexDenisov/FontasticIcons#15]
What do you guys think? I know 3 popular alternatives:
1. OCUnit (default underlying others)
2. [Kiwi](https://github.com/allending/Kiwi/blob/master/Readme.md) (most popular for BDD see also [Cedar](https://github.com/pivotal/cedar/blob/master/README.markdown))
3. [Specta](https://github.com/petejkim/specta/blob/master/README.md) (@github supports it and I personally use their ReactiveCocoa, Mantle, and libextobjc projects extensively)
4. [Etcetra](http://www.alexcurylo.com/blog/2012/03/10/roundup-testing/)

I also left a `TODO` in my upcoming patch. Thoughts?

**Comment by AlexDenisov** [comment]
I've prefer to use Cedar. I think it's more pretty and has more [laconic matchers](https://github.com/AlexDenisov/iActiveRecord/blob/master/UnitTests/DynamicAccessorSpec.mm#L73), moreover I like rspec syntax, it looks much better than 'fat' OCUnit-like specs. 
Also I didn't like Bundle tests, as I know there is no way to run them from terminal.

btw, this is a good occasion to try [travis-ci](https://github.com/soffes/sskeychain/blob/master/.travis.yml).

**Comment by texastoland** [comment]
If you're already using it that's enough reason for me. Have you looked at Kiwi or Specta? I found articles about their CI integration [[1](http://9elements.com/io/index.php/continuous-integration-of-ios-projects-using-jenkins-cocoapods-and-kiwi/)][[2](http://www.raingrove.com/2012/03/28/running-ocunit-and-specta-tests-from-command-line.html)] too. Cedar's C++ matchers are genius! But the documentation says they're broken for ARC and use Expecta instead (the sister library of Specta). And Kiwi's matchers look prettier than Expecta's to me.

**Comment by AlexDenisov** [comment]
I've used Kiwi, Expecta and Cedar. And Cedar is better, imho. 
And yes, Cedar target should not support ARC, but I didn't have any problems with this, even if main target uses ARC. Yes, we may have some leaks, but for unit tests this is not critical.

**Comment by AlexDenisov** [comment]
@dnalot, could you share your thoughts? What framework do you use or what prefer?

**Comment by texastoland** [comment]
Wow I'm impressed :smile_cat: The last time I did BDD was [specs](http://etorreborre.github.com/specs2/guide/org.specs2.guide.QuickStart.html) for Scala a couple years ago so I'm happy you've already tried a few. Rereading the [README](https://github.com/pivotal/cedar/blob/master/README.markdown#matchers-and-arc) matchers still work by disabling ARC just for specs. So sounds good to me :+1:

**Comment by AlexDenisov** [comment]
That's great, so I will start after you finish #13, to avoid a .pbxproj merge hell :smile:

**Comment by texastoland** [comment]
:boom:

**Comment by texastoland** [comment]
Opinions on docstrings?

**Comment by AlexDenisov** [comment]
What are you mean under `docstrings`? `appledoc`?

Sorry, I do not fully understand =(

**Comment by texastoland** [comment]
Yeah AppleDoc (generated by CocoaPods), Doxygen (no personal experience), HeaderDoc (Apple), TomDoc (@github but poorly supported).

**Comment by AlexDenisov** [comment]
+1
I've never used this before, so I'm very interested to try it :)

**Comment by texastoland** [comment]
Cool! I prefer AppleDoc personally but let you investigate until it's on the roadmap :smiley_cat:

**Comment by AlexDenisov** [comment]
I have not used any documentation generators yet, so I trust to your experience. If you know how to use appledoc, then let's use appledoc. But if you want to study some new system - let's try something new ;)
