### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by AlexDenisov** [AlexDenisov/FontasticIcons#18]

**Comment by texastoland** [comment]
It looks like the primary changes will be extending `FIIconView` from `NSView` and replacing `+layerClass` with `-setLayer:` and `-setWantsLayer:YES` testing for compatibility back to 10.6-ish. This sounds easy enough for `#ifdef`s. Will target new `osx-support-18` branch until we have real tests #15 when it should be merged to `development` until an accompanying sample then `master`.
