### ISSUE TITLE
Pimp Up Sample

### ISSUE THREAD

**Issue by texastoland** [AlexDenisov/FontasticIcons#23]
The sample renders Font Awesome noticeably slow because its controller doesn't defer rendering.
- [ ] ~~Either table view with N icons per row or~~ iOS 6-only collection view or [GMGridView](https://github.com/gmoledina/GMGridView)
- [ ] Refactor into storyboard
- [ ] Magnify icon on tap
- [ ] Zoom and rotate fullscreen icon
- [ ] Control/gesture to scale stroke
- [ ] Fuzzy search header in icon list

**Comment by AlexDenisov** [comment]
Totally agree, I've used this slow implementation just to check that all fonts rendered as needed.

**Comment by AlexDenisov** [comment]
+1 storyboard

**Comment by texastoland** [comment]
:jack_o_lantern:

**Comment by texastoland** [comment]
Old school table view or iOS 6-only collection view?

**Comment by AlexDenisov** [comment]
Collection view enough for sample, IMO.

**Comment by texastoland** [comment]
[GMGridView](http://www.youtube.com/watch?v=qK-qULlvAv4) supports new features in my description (gesture zoom/rotate) and could be limited to target the sample? I've also been wondering whether samples belong in separate projects? _**Update:** links to video demo._
