### ISSUE TITLE
FIFontAwesomeIcon's font name should use class method?

### ISSUE THREAD

**Issue by mave99a** [AlexDenisov/FontasticIcons#25]
@interface FIFontAwesomeIcon (Forwarding)
- (instancetype)glass;
- (instancetype)music;
- (instancetype)search;
- (instancetype)envelope;

Should they be '+' instead of '-'  ?

**Comment by AlexDenisov** [comment]
Could you explain reasons? :smile:

**Comment by mave99a** [comment]
I mean the icon names in 
https://github.com/AlexDenisov/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIFontAwesomeIcon.h

compare to those defined in: 
https://github.com/AlexDenisov/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIEntypoIcon.h

or 
https://github.com/AlexDenisov/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIEntypoSocialIcon.h

**Comment by AlexDenisov** [comment]
Oh, you're right.
That's my fault.
I will fix this.

**Comment by mave99a** [comment]
Thanks a lot!  Can you pls. also update pod spec?   

This is a great project I used in my apps and works well.

**Comment by AlexDenisov** [comment]
Yep, sure. I will update all stuff.

**Comment by AlexDenisov** [comment]
Done.
