### ISSUE TITLE
Refactor FIIconView into FIIconLayer

### ISSUE THREAD

**Issue by texastoland** [AlexDenisov/FontasticIcons#7]
Struggling with simply setting icons to buttons I wondered whether it'd be more accessible implementing rasterization subclassing CALayer that could be composed into any UIView?

**Comment by AlexDenisov** [comment]
I thought about implementing something like this

```
@interface FIIcon : NSObject
...
- (UIImage *)iconImageOfSize:(CGSize)imageSize;
...
@end
```

But I like your idea.
BTW, feel free to open pull request ;)

**Comment by texastoland** [comment]
I did just that in my current project :)

``` objc
@interface FIIcon (DLFontasticIcons)

+ (FIIcon *)iconWithName:(NSString *)iconName fontSetName:(NSString *)fontName;
- (UIImage *)renderWithFrame:(CGRect)frame color:(UIColor *)color;
@end
```

Where frame bundles padding with size. I'll send one soon!

**Comment by texastoland** [comment]
Done all of the above. Pull request on its way.

**Comment by AlexDenisov** [comment]
:+1:

**Comment by AlexDenisov** [comment]
Solved by #8.

**Comment by texastoland** [comment]
[Pushed](https://github.com/CocoaPods/Specs/commit/71af13db66f299b690c85d69b5942db1387a07c9) to @CocoaPods.

**Comment by AlexDenisov** [comment]
Thank you, I've added new tag.
